### ISSUE TITLE
Integração com Github

### ISSUE THREAD

**Issue by rdenadai** [milharal-dev/detona-dev#10]
Adicionar chamada a API do Github.
Dado um nome de usuário, carregar seu perfil e seus repositórios.
Os 3 repositórios que tiverem + stars, coletar também randômicamente alguns arquivos para analisar código existente.
Não sei se será possível rodar alguma ferramenta de análise ciclomatica de código, se não for, talvez mandar pequenos chunks (ver a validade disso).

Procurar uma lib que integre com o Github.

**Comment by mattpsvreis** [comment]
Inicialmente vai pegar apenas o 5 repositórios mais atualizados e ler os READMEs.
