### ISSUE TITLE
Adicionar backend

### ISSUE THREAD

**Issue by rdenadai** [milharal-dev/detona-dev#3]
Adicionar a configuração inicial do backend do projeto.
O @mattpsvreis criou o esqueto inicial do frontend do projeto, mas foi acordado q o backend tb estará neste repositório.

Backend: `Express + Node`

**Comment by mattpsvreis** [comment]
Farei.

**Comment by mattpsvreis** [comment]
Express vai ser feito pelo @VINNE7 na Issue #9
